language: rust

os:
  - linux
  - osx

cache: cargo

addons:
  apt:
    packages:
      - libpcap-dev
      - upx-ucl
      - graphviz

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install upx graphviz; fi

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script: make install_deps; make all
